# Generated by Django 5.0b1 on 2023-11-02 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="apartmentvisit",
            name="house",
        ),
        migrations.RemoveField(
            model_name="housevisit",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="housevisit",
            name="house",
        ),
        migrations.DeleteModel(
            name="People",
        ),
        migrations.RenameField(
            model_name="house",
            old_name="address",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="house",
            old_name="entrances_count",
            new_name="entrances",
        ),
        migrations.AddField(
            model_name="campaign",
            name="houses",
            field=models.ManyToManyField(to="promo.house"),
        ),
        migrations.AddField(
            model_name="house",
            name="number",
            field=models.CharField(default=datetime.date.today(), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="house",
            name="street",
            field=models.CharField(default=datetime.date.today(), max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ApartmentVisit",
        ),
        migrations.DeleteModel(
            name="HouseVisit",
        ),
    ]
